/*
 * File: app/view/MyMap.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyMap', {
    extend: 'Ext.Map',

    config: {
        mapOptions: '{        \n    center: new google.maps.LatLng(41.972176, 2.819539),\n    zoom: 12\n}'
    },

    initialize: function() {
        var me = this;
        console.log("In initialize function i am:" + this.self.getName());
        var position = new google.maps.LatLng(41.987399,2.826215); // Catedral de girona

        new Ext.util.DelayedTask(function () {
            if (this!=me){
                console.log("In delayed task i am a different me");
            }
            me.setMapOptions({ 
                title: '#' + 1,
                useCurrentLocation: false,
                autoCenter: true,
                center: position,
            zoom: 16 });

            youAreHere.setMap(me.getMap());

            marker.setMap(me.getMap());

            flightPath.setMap(me.getMap()); 

            for (var i = flightPath.getPath().getLength() - 1; i > 0; i--) {
                var marker2 = new google.maps.Marker({
                    position: flightPath.getPath().getAt(i),
                    title: '#' + i,
                    map: me.getMap()
                });
            }   
        }).delay(3000);


        var googleMap = this.getMap();

        var marker = new google.maps.Marker({
            position: position,
            map: googleMap
        });

        // var newIcon = MapIconMaker.createMarkerIcon({width: 20, height: 34, primaryColor: "#0000FF", cornercolor:"#0000FF"});

        var youAreHere = new google.maps.Marker({
            position: new google.maps.LatLng(41.986699,2.824143), // Mig del pont
            map: googleMap,
            icon: 'blue_MarkerA.png'
        });

        var infowindow = new google.maps.InfoWindow({
            content: '<img src="Jardines de la catedral de Girona.jpg" alt="logo" width="50" height="44" aligh="left"/>Catedral de girona<br>'
        });

        google.maps.event.addListener(marker, 'click', function(){
            //infowindow.open(map,marker);
            console.log('Tapped');
            var myTabPanel = Ext.create('MyApp.view.MyTabPanel');
            var myCarousel = Ext.create('MyApp.view.MyCarousel');
            Ext.Viewport.add(myTabPanel);
            myTabPanel.show();
        });

        // google.maps.event.addListener(googleMap, 'click', function(event) {
        //     addMarker(event.latLng);
        // });   

        function addMarker(location) {
            marker = new google.maps.Marker({
                position: location,
                map: googleMap
            });
            marker.setMap(googleMap);
        }

        var flightPlanCoordinates = [
        new google.maps.LatLng(41.987399,2.826215), // Catedral
        new google.maps.LatLng(41.98692,2.826536), // Museu d'art
        new google.maps.LatLng(41.988326,2.825574), // Banys arebs
        new google.maps.LatLng(41.986566,2.828088) // Muralla
        ];

        var flightPath = new google.maps.Polyline({
            path: flightPlanCoordinates,
            strokeColor: "#FF0000",
            strokeOpacity: 1.0,
            strokeWeight: 2
        });

    }

});