/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',

    config: {
        items: [
            {
                xtype: 'container',
                title: 'The Cathedral',
                iconCls: 'info',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'carousel',
                        flex: 1,
                        items: [
                            {
                                xtype: 'container',
                                html: '        <div id="cathedral">             <div id="rounded_box">                 <section id="content">                     <h1>                         La catedral de Girona                     </h1>                     <h2>                         Intro                     </h2>                     <blockquote class="style1">                         <span>Iniciada per l\'absis i concebuda en principi coma una esglèsia de tres naus, es va construir entre els ansy 1312 i 1347</span>                     </blockquote>                     <h2>                         Did you know?                     </h2>                     <blockquote class="style1">                         <span>Iniciada per l\'absis i concebuda en principi coma una esglèsia de tres naus, es va construir entre els ansy 1312 i 1347</span>                     </blockquote>                </section>             </div>         </div> '
                            },
                            {
                                xtype: 'container',
                                html: '        <div id="cathedral">             <div id="rounded_box">                 <section id="content">                     <h1>                         The quests                     </h1>                     <blockquote class="style2">                         <div id="list2">                             <ol>                                 <li>                                                                          <p>                                         <span style="font-family: \'MuseoSlab300\', sans-serif;color: #434e3c;font-size: 17px;font-weight: bold;letter-spacing: -1px;">The Gargoiles</span><em>Cathedrals are full of garloiles.</em><em>Find the nastiest!</em>                                     </p>                                 </li>                                  <li>                                                                          <p>                                         <span style="font-family: \'MuseoSlab300\', sans-serif;color: #434e3c;font-size: 17px;font-weight: bold;letter-spacing: -1px;">The Mummies</span><em> Did you know that cathedrals have </em> <em>mummies too?. They are the remains of </em><em>old kings!</em>                                     </p>                                 </li>                             </ol>                         </div>                     </blockquote>                  </section>             </div>         </div> '
                            },
                            {
                                xtype: 'container',
                                html: '        <div id="cathedral">             <div id="rounded_box">                 <section id="content">                     <h1>                         La catedral de Girona                     </h1>                     <h2>                         Intro                     </h2>                     <blockquote class="style1">                         <span>Iniciada per l\'absis i concebuda en principi coma una esglèsia de tres naus, es va construir entre els ansy 1312 i 1347</span>                     </blockquote>                     <h2>                         Did you know?                     </h2>                     <blockquote class="style1">                         <span>Iniciada per l\'absis i concebuda en principi coma una esglèsia de tres naus, es va construir entre els ansy 1312 i 1347</span>                     </blockquote>                </section>             </div>         </div> '
                            },
                            {
                                xtype: 'container',
                                html: '        <div id="cathedral">             <div id="rounded_box">                 <section id="content">                     <h1>                         La catedral de Girona                     </h1>                     <h2>                         Intro                     </h2>                     <blockquote class="style1">                         <span>Iniciada per l\'absis i concebuda en principi coma una esglèsia de tres naus, es va construir entre els ansy 1312 i 1347</span>                     </blockquote>                     <h2>                         Did you know?                     </h2>                     <blockquote class="style1">                         <span>Iniciada per l\'absis i concebuda en principi coma una esglèsia de tres naus, es va construir entre els ansy 1312 i 1347</span>                     </blockquote>                </section>             </div>         </div> '
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Art Museum',
                iconCls: 'info',
                html: 'The art museum'
            },
            {
                xtype: 'container',
                title: 'Arab Baths',
                iconCls: 'info',
                html: 'The Arab Baths'
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});