/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    views: [
        'MyMap',
        'MyTabPanel'
    ],
    controllers: [
        'MyController'
    ],
    name: 'MyApp',
    startupImage: {
        '320x460': 'resources/startup/splashScreen.png'
    },

    launch: function() {
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            message: 'Loading, please wait'
        });

        var position = new google.maps.LatLng(41.987399,2.826215); // Catedral de girona

        new Ext.util.DelayedTask(function () {
            Ext.Viewport.setMasked(false);
            map.setMapOptions({ 
                title: '#' + 1,
                useCurrentLocation: false,
                autoCenter: true,
                center: position,
            zoom: 16 });
            youAreHere.setMap(map.getMap());
            marker.setMap(map.getMap());
            flightPath.setMap(map.getMap()); 
            for (var i = flightPath.getPath().getLength() - 1; i > 0; i--) {
                var marker2 = new google.maps.Marker({
                    position: flightPath.getPath().getAt(i),
                    title: '#' + i,
                    map: map.getMap()
                });
            }   
        }).delay(3000);


        var map = Ext.create('MyApp.view.MyMap', {fullscreen: true});
        var googleMap = map.getMap();

        var marker = new google.maps.Marker({
            position: position,
            map: googleMap
        });

        // var newIcon = MapIconMaker.createMarkerIcon({width: 20, height: 34, primaryColor: "#0000FF", cornercolor:"#0000FF"});

        var youAreHere = new google.maps.Marker({
            position: new google.maps.LatLng(41.986699,2.824143), // Mig del pont
            map: googleMap,
            icon: 'blue_MarkerA.png'
        });

        var infowindow = new google.maps.InfoWindow({
            content: '<img src="Jardines de la catedral de Girona.jpg" alt="logo" width="50" height="44" aligh="left"/>Catedral de girona<br>'
        });

        google.maps.event.addListener(marker, 'click', function(){
            //infowindow.open(map,marker);
            // Ext.Viewport.add(Ext.create('MyApp.view.MyTabPanel'));
            console.log('Tapped');
        });

        // google.maps.event.addListener(googleMap, 'click', function(event) {
        //     addMarker(event.latLng);
        // });   

        function addMarker(location) {
            marker = new google.maps.Marker({
                position: location,
                map: googleMap
            });
            marker.setMap(googleMap);
        }

        var flightPlanCoordinates = [
        new google.maps.LatLng(41.987399,2.826215), // Catedral
        new google.maps.LatLng(41.98692,2.826536), // Museu d'art
        new google.maps.LatLng(41.988326,2.825574), // Banys arebs
        new google.maps.LatLng(41.986566,2.828088) // Muralla
        ];

        var flightPath = new google.maps.Polyline({
            path: flightPlanCoordinates,
            strokeColor: "#FF0000",
            strokeOpacity: 1.0,
            strokeWeight: 2
        });


        Ext.create('MyApp.view.MyMap', {fullscreen: true});
    }

});
